title: What to code when bored!
description: its actually right!!
template:
  repo: what-to-code-when-bored!-template
  name: what-to-code-when-bored!
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
